// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpNameOfDemo")>]
[<assembly: AssemblyProductAttribute("FSharpNameOfDemo")>]
[<assembly: AssemblyDescriptionAttribute("F# nameof prototype")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpNameOfDemo"
    let [<Literal>] AssemblyProduct = "FSharpNameOfDemo"
    let [<Literal>] AssemblyDescription = "F# nameof prototype"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
